apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    app: influxdb
  name: influxdb
  selfLink: /apis/apps/v1/namespaces/default/deployments/influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: influxdb-creds
        image: influxdb:latest
        imagePullPolicy: Always
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb-cluster-ip
  selfLink: /api/v1/namespaces/default/services/influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: influxdb-creds
  selfLink: /api/v1/namespaces/default/secrets/influxdb-creds
type: Opaque
data:
  #INFLUXDB_DATABASE => twittergraph 
  #INFLUXDB_HOST => influxdb
  #INFLUXDB_PASSWORD => root 
  #INFLUXDB_USERNAME => root 
  INFLUXDB_DATABASE: dHdpdHRlcmdyYXBo
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_USERNAME: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: influxdb-nodeport
  selfLink: /api/v1/namespaces/default/services/influxdb-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31948
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  sessionAffinity: None
  type: NodePort
