kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: 10.71.69.236:5000/spark-hadoop-new:2.4.4
          command: ["/spark-worker.sh"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
