---

apiVersion: v1

kind: Service

metadata:

  name: kafka-service-2

  labels:

    name: kafka

spec:

  ports:

  - port: 9092

    nodePort: 31118

    name: kafka-port

    protocol: TCP

  selector:

    app: kafka

    id: "2"

  type: LoadBalancer
