---

kind: Deployment

apiVersion: apps/v1

metadata:

  name: kafka-broker-1

spec:
  selector:
    matchLabels:
      app: kafka
  template:

    metadata:

      labels:

        app: kafka

        id: "1"

    spec:

      containers:

      - name: kafka

        image: wurstmeister/kafka

        ports:

        - containerPort: 9092

        env:

        - name: KAFKA_ADVERTISED_PORT

          value: "31117"

        - name: KAFKA_ADVERTISED_HOST_NAME

          value: 10.71.69.236

        - name: KAFKA_ZOOKEEPER_CONNECT

          value: zoo1:2181

        - name: KAFKA_BROKER_ID

          value: "1"

     #  - name: KAFKA_CREATE_TOPICS

     #    value: tweeter-topic:2:2
