---

apiVersion: v1

kind: Service

metadata:

  name: kafka-service-1

  labels:

    name: kafka

spec:

  ports:

  - port: 9092

    nodePort: 31117

    name: kafka-port

    protocol: TCP

  selector:

    app: kafka

    id: "1"

  type: LoadBalancer
