---

apiVersion: v1

kind: Service

metadata:

  name: kafka-service-3

  labels:

    name: kafka

spec:

  ports:

  - port: 9092

    nodePort: 31119

    name: kafka-port

    protocol: TCP

  selector:

    app: kafka

    id: "3"

  type: LoadBalancer
